name: Jupyter Server Tests [Linux]

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files --hook-stage=manual

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Install the Python dependencies
        run: |
          pip install -e ".[test]" codecov
      - name: List installed packages
        run: |
          pip freeze
          pip check
      - name: Run the tests
        if: ${{ matrix.python-version != 'pypy-3.7' }}
        run: |
          pytest -vv jupyter_server --cov jupyter_server --cov-branch --cov-report term-missing:skip-covered
      - name: Run the tests on pypy
        if: ${{ matrix.python-version == 'pypy-3.7' }}
        run: |
          pytest -vv jupyter_server
      - name: Install the Python dependencies for the examples
        run: |
          cd examples/simple && pip install -e .
      - name: Run the tests for the examples
        run: |
          pytest examples/simple
      - name: Coverage
        if: ${{ matrix.python-version != 'pypy-3.7' }}
        run: |
          codecov
      - name: Test the docs
        run: |
          cd docs
          pip install -r doc-requirements.txt
          make html SPHINXOPTS="-W"

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Build SDist
        run: |
          pip install build
          python -m build --sdist
      - uses: actions/upload-artifact@v2
        with:
          name: "sdist"
          path: dist/*.tar.gz

  test_sdist:
    runs-on: ubuntu-latest
    needs: [make_sdist]
    name: Install from SDist and Test
    steps:
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Download sdist
        uses: actions/download-artifact@v2
      - name: Install From SDist
        run: |
          pip install --find-links=./sdist "jupyter_server[test]>=0.0.dev0"
          pip install pytest-github-actions-annotate-failures
      - name: Run Test
        run: pytest -vv --pyargs --timeout=300 --timeout_method=thread jupyter_server --capture=no
